// Mocks generated by Mockito 5.4.4 from annotations
// in exhibition_buyer_app/test/providers/flag_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:exhibition_buyer_app/core/services/realtime_service.dart'
    as _i7;
import 'package:exhibition_buyer_app/features/flag/models/flag.dart' as _i2;
import 'package:exhibition_buyer_app/features/flag/services/flag_service.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:realtime_client/src/constants.dart' as _i10;
import 'package:realtime_client/src/push.dart' as _i4;
import 'package:realtime_client/src/types.dart' as _i9;
import 'package:supabase_flutter/supabase_flutter.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFlag_0 extends _i1.SmartFake implements _i2.Flag {
  _FakeFlag_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeChannel_1 extends _i1.SmartFake
    implements _i3.RealtimeChannel {
  _FakeRealtimeChannel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePush_2 extends _i1.SmartFake implements _i4.Push {
  _FakePush_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimePresence_3 extends _i1.SmartFake
    implements _i3.RealtimePresence {
  _FakeRealtimePresence_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeClient_4 extends _i1.SmartFake
    implements _i3.RealtimeClient {
  _FakeRealtimeClient_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FlagService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlagService extends _i1.Mock implements _i5.FlagService {
  MockFlagService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Flag> createFlag({
    required String? photoId,
    required double? positionX,
    required double? positionY,
    required String? createdBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFlag,
          [],
          {
            #photoId: photoId,
            #positionX: positionX,
            #positionY: positionY,
            #createdBy: createdBy,
          },
        ),
        returnValue: _i6.Future<_i2.Flag>.value(_FakeFlag_0(
          this,
          Invocation.method(
            #createFlag,
            [],
            {
              #photoId: photoId,
              #positionX: positionX,
              #positionY: positionY,
              #createdBy: createdBy,
            },
          ),
        )),
      ) as _i6.Future<_i2.Flag>);

  @override
  _i6.Future<List<_i2.Flag>> getFlags(String? photoId) => (super.noSuchMethod(
        Invocation.method(
          #getFlags,
          [photoId],
        ),
        returnValue: _i6.Future<List<_i2.Flag>>.value(<_i2.Flag>[]),
      ) as _i6.Future<List<_i2.Flag>>);

  @override
  _i6.Future<_i2.Flag?> getFlag(String? flagId) => (super.noSuchMethod(
        Invocation.method(
          #getFlag,
          [flagId],
        ),
        returnValue: _i6.Future<_i2.Flag?>.value(),
      ) as _i6.Future<_i2.Flag?>);

  @override
  _i6.Future<int> getNextFlagNumber(String? photoId) => (super.noSuchMethod(
        Invocation.method(
          #getNextFlagNumber,
          [photoId],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<_i2.Flag> updateBuyerPrice({
    required String? flagId,
    required double? priceRmb,
    String? formula,
    String? teamId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBuyerPrice,
          [],
          {
            #flagId: flagId,
            #priceRmb: priceRmb,
            #formula: formula,
            #teamId: teamId,
          },
        ),
        returnValue: _i6.Future<_i2.Flag>.value(_FakeFlag_0(
          this,
          Invocation.method(
            #updateBuyerPrice,
            [],
            {
              #flagId: flagId,
              #priceRmb: priceRmb,
              #formula: formula,
              #teamId: teamId,
            },
          ),
        )),
      ) as _i6.Future<_i2.Flag>);

  @override
  _i6.Future<_i2.Flag> setTargetPrice({
    required String? flagId,
    required double? targetPrice,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTargetPrice,
          [],
          {
            #flagId: flagId,
            #targetPrice: targetPrice,
          },
        ),
        returnValue: _i6.Future<_i2.Flag>.value(_FakeFlag_0(
          this,
          Invocation.method(
            #setTargetPrice,
            [],
            {
              #flagId: flagId,
              #targetPrice: targetPrice,
            },
          ),
        )),
      ) as _i6.Future<_i2.Flag>);

  @override
  _i6.Future<_i2.Flag> updateFlag({
    required String? flagId,
    double? priceRmb,
    double? priceConverted,
    double? targetPrice,
    double? positionX,
    double? positionY,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFlag,
          [],
          {
            #flagId: flagId,
            #priceRmb: priceRmb,
            #priceConverted: priceConverted,
            #targetPrice: targetPrice,
            #positionX: positionX,
            #positionY: positionY,
          },
        ),
        returnValue: _i6.Future<_i2.Flag>.value(_FakeFlag_0(
          this,
          Invocation.method(
            #updateFlag,
            [],
            {
              #flagId: flagId,
              #priceRmb: priceRmb,
              #priceConverted: priceConverted,
              #targetPrice: targetPrice,
              #positionX: positionX,
              #positionY: positionY,
            },
          ),
        )),
      ) as _i6.Future<_i2.Flag>);

  @override
  _i6.Future<_i2.Flag> updateFlagPosition({
    required String? flagId,
    required double? positionX,
    required double? positionY,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFlagPosition,
          [],
          {
            #flagId: flagId,
            #positionX: positionX,
            #positionY: positionY,
          },
        ),
        returnValue: _i6.Future<_i2.Flag>.value(_FakeFlag_0(
          this,
          Invocation.method(
            #updateFlagPosition,
            [],
            {
              #flagId: flagId,
              #positionX: positionX,
              #positionY: positionY,
            },
          ),
        )),
      ) as _i6.Future<_i2.Flag>);

  @override
  _i6.Future<void> deleteFlag(String? flagId) => (super.noSuchMethod(
        Invocation.method(
          #deleteFlag,
          [flagId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> recalculatePrices({
    required String? photoId,
    required String? formula,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recalculatePrices,
          [],
          {
            #photoId: photoId,
            #formula: formula,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i3.RealtimeChannel subscribeFlagChanges({
    required String? photoId,
    required void Function(_i2.Flag)? onInsert,
    required void Function(_i2.Flag)? onUpdate,
    required void Function(String)? onDelete,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeFlagChanges,
          [],
          {
            #photoId: photoId,
            #onInsert: onInsert,
            #onUpdate: onUpdate,
            #onDelete: onDelete,
          },
        ),
        returnValue: _FakeRealtimeChannel_1(
          this,
          Invocation.method(
            #subscribeFlagChanges,
            [],
            {
              #photoId: photoId,
              #onInsert: onInsert,
              #onUpdate: onUpdate,
              #onDelete: onDelete,
            },
          ),
        ),
      ) as _i3.RealtimeChannel);
}

/// A class which mocks [RealtimeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtimeService extends _i1.Mock implements _i7.RealtimeService {
  MockRealtimeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.RealtimeChannel subscribeToBooths(
    String? eventId,
    dynamic Function(dynamic)? onUpdate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToBooths,
          [
            eventId,
            onUpdate,
          ],
        ),
        returnValue: _FakeRealtimeChannel_1(
          this,
          Invocation.method(
            #subscribeToBooths,
            [
              eventId,
              onUpdate,
            ],
          ),
        ),
      ) as _i3.RealtimeChannel);

  @override
  _i3.RealtimeChannel subscribeToPhotos(
    String? boothId,
    dynamic Function(dynamic)? onUpdate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToPhotos,
          [
            boothId,
            onUpdate,
          ],
        ),
        returnValue: _FakeRealtimeChannel_1(
          this,
          Invocation.method(
            #subscribeToPhotos,
            [
              boothId,
              onUpdate,
            ],
          ),
        ),
      ) as _i3.RealtimeChannel);

  @override
  _i3.RealtimeChannel subscribeToFlags(
    String? photoId,
    dynamic Function(dynamic)? onUpdate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToFlags,
          [
            photoId,
            onUpdate,
          ],
        ),
        returnValue: _FakeRealtimeChannel_1(
          this,
          Invocation.method(
            #subscribeToFlags,
            [
              photoId,
              onUpdate,
            ],
          ),
        ),
      ) as _i3.RealtimeChannel);

  @override
  _i3.RealtimeChannel subscribeToEvents(
    String? teamId,
    dynamic Function(dynamic)? onUpdate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToEvents,
          [
            teamId,
            onUpdate,
          ],
        ),
        returnValue: _FakeRealtimeChannel_1(
          this,
          Invocation.method(
            #subscribeToEvents,
            [
              teamId,
              onUpdate,
            ],
          ),
        ),
      ) as _i3.RealtimeChannel);

  @override
  _i3.RealtimeChannel subscribeToFormulaHistory(
    String? teamId,
    dynamic Function(dynamic)? onUpdate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToFormulaHistory,
          [
            teamId,
            onUpdate,
          ],
        ),
        returnValue: _FakeRealtimeChannel_1(
          this,
          Invocation.method(
            #subscribeToFormulaHistory,
            [
              teamId,
              onUpdate,
            ],
          ),
        ),
      ) as _i3.RealtimeChannel);

  @override
  _i3.RealtimeChannel subscribeToExchangeSettings(
    String? teamId,
    dynamic Function(dynamic)? onUpdate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToExchangeSettings,
          [
            teamId,
            onUpdate,
          ],
        ),
        returnValue: _FakeRealtimeChannel_1(
          this,
          Invocation.method(
            #subscribeToExchangeSettings,
            [
              teamId,
              onUpdate,
            ],
          ),
        ),
      ) as _i3.RealtimeChannel);

  @override
  _i6.Future<void> unsubscribe(_i3.RealtimeChannel? channel) =>
      (super.noSuchMethod(
        Invocation.method(
          #unsubscribe,
          [channel],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> unsubscribeAll() => (super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RealtimeChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtimeChannel extends _i1.Mock implements _i3.RealtimeChannel {
  MockRealtimeChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get joinedOnce => (super.noSuchMethod(
        Invocation.getter(#joinedOnce),
        returnValue: false,
      ) as bool);

  @override
  set joinedOnce(bool? _joinedOnce) => super.noSuchMethod(
        Invocation.setter(
          #joinedOnce,
          _joinedOnce,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Push get joinPush => (super.noSuchMethod(
        Invocation.getter(#joinPush),
        returnValue: _FakePush_2(
          this,
          Invocation.getter(#joinPush),
        ),
      ) as _i4.Push);

  @override
  set joinPush(_i4.Push? _joinPush) => super.noSuchMethod(
        Invocation.setter(
          #joinPush,
          _joinPush,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.RealtimePresence get presence => (super.noSuchMethod(
        Invocation.getter(#presence),
        returnValue: _FakeRealtimePresence_3(
          this,
          Invocation.getter(#presence),
        ),
      ) as _i3.RealtimePresence);

  @override
  set presence(_i3.RealtimePresence? _presence) => super.noSuchMethod(
        Invocation.setter(
          #presence,
          _presence,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get broadcastEndpointURL => (super.noSuchMethod(
        Invocation.getter(#broadcastEndpointURL),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#broadcastEndpointURL),
        ),
      ) as String);

  @override
  set broadcastEndpointURL(String? _broadcastEndpointURL) => super.noSuchMethod(
        Invocation.setter(
          #broadcastEndpointURL,
          _broadcastEndpointURL,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get subTopic => (super.noSuchMethod(
        Invocation.getter(#subTopic),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#subTopic),
        ),
      ) as String);

  @override
  String get topic => (super.noSuchMethod(
        Invocation.getter(#topic),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#topic),
        ),
      ) as String);

  @override
  Map<String, dynamic> get params => (super.noSuchMethod(
        Invocation.getter(#params),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  set params(Map<String, dynamic>? _params) => super.noSuchMethod(
        Invocation.setter(
          #params,
          _params,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.RealtimeClient get socket => (super.noSuchMethod(
        Invocation.getter(#socket),
        returnValue: _FakeRealtimeClient_4(
          this,
          Invocation.getter(#socket),
        ),
      ) as _i3.RealtimeClient);

  @override
  bool get canPush => (super.noSuchMethod(
        Invocation.getter(#canPush),
        returnValue: false,
      ) as bool);

  @override
  String get joinRef => (super.noSuchMethod(
        Invocation.getter(#joinRef),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#joinRef),
        ),
      ) as String);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool get isErrored => (super.noSuchMethod(
        Invocation.getter(#isErrored),
        returnValue: false,
      ) as bool);

  @override
  bool get isJoined => (super.noSuchMethod(
        Invocation.getter(#isJoined),
        returnValue: false,
      ) as bool);

  @override
  bool get isJoining => (super.noSuchMethod(
        Invocation.getter(#isJoining),
        returnValue: false,
      ) as bool);

  @override
  bool get isLeaving => (super.noSuchMethod(
        Invocation.getter(#isLeaving),
        returnValue: false,
      ) as bool);

  @override
  void rejoinUntilConnected() => super.noSuchMethod(
        Invocation.method(
          #rejoinUntilConnected,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.RealtimeChannel subscribe([
    void Function(
      _i3.RealtimeSubscribeStatus,
      Object?,
    )? callback,
    Duration? timeout,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [
            callback,
            timeout,
          ],
        ),
        returnValue: _FakeRealtimeChannel_1(
          this,
          Invocation.method(
            #subscribe,
            [
              callback,
              timeout,
            ],
          ),
        ),
      ) as _i3.RealtimeChannel);

  @override
  List<_i3.SinglePresenceState> presenceState() => (super.noSuchMethod(
        Invocation.method(
          #presenceState,
          [],
        ),
        returnValue: <_i3.SinglePresenceState>[],
      ) as List<_i3.SinglePresenceState>);

  @override
  _i6.Future<_i3.ChannelResponse> track(
    Map<String, dynamic>? payload, [
    Map<String, dynamic>? opts = const {},
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #track,
          [
            payload,
            opts,
          ],
        ),
        returnValue:
            _i6.Future<_i3.ChannelResponse>.value(_i3.ChannelResponse.ok),
      ) as _i6.Future<_i3.ChannelResponse>);

  @override
  _i6.Future<_i3.ChannelResponse> untrack(
          [Map<String, dynamic>? opts = const {}]) =>
      (super.noSuchMethod(
        Invocation.method(
          #untrack,
          [opts],
        ),
        returnValue:
            _i6.Future<_i3.ChannelResponse>.value(_i3.ChannelResponse.ok),
      ) as _i6.Future<_i3.ChannelResponse>);

  @override
  _i3.RealtimeChannel onPostgresChanges({
    required _i3.PostgresChangeEvent? event,
    String? schema,
    String? table,
    _i3.PostgresChangeFilter? filter,
    required void Function(_i3.PostgresChangePayload)? callback,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #onPostgresChanges,
          [],
          {
            #event: event,
            #schema: schema,
            #table: table,
            #filter: filter,
            #callback: callback,
          },
        ),
        returnValue: _FakeRealtimeChannel_1(
          this,
          Invocation.method(
            #onPostgresChanges,
            [],
            {
              #event: event,
              #schema: schema,
              #table: table,
              #filter: filter,
              #callback: callback,
            },
          ),
        ),
      ) as _i3.RealtimeChannel);

  @override
  _i3.RealtimeChannel onBroadcast({
    required String? event,
    required void Function(Map<String, dynamic>)? callback,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #onBroadcast,
          [],
          {
            #event: event,
            #callback: callback,
          },
        ),
        returnValue: _FakeRealtimeChannel_1(
          this,
          Invocation.method(
            #onBroadcast,
            [],
            {
              #event: event,
              #callback: callback,
            },
          ),
        ),
      ) as _i3.RealtimeChannel);

  @override
  _i3.RealtimeChannel onPresenceSync(
          void Function(_i3.RealtimePresenceSyncPayload)? callback) =>
      (super.noSuchMethod(
        Invocation.method(
          #onPresenceSync,
          [callback],
        ),
        returnValue: _FakeRealtimeChannel_1(
          this,
          Invocation.method(
            #onPresenceSync,
            [callback],
          ),
        ),
      ) as _i3.RealtimeChannel);

  @override
  _i3.RealtimeChannel onPresenceJoin(
          void Function(_i3.RealtimePresenceJoinPayload)? callback) =>
      (super.noSuchMethod(
        Invocation.method(
          #onPresenceJoin,
          [callback],
        ),
        returnValue: _FakeRealtimeChannel_1(
          this,
          Invocation.method(
            #onPresenceJoin,
            [callback],
          ),
        ),
      ) as _i3.RealtimeChannel);

  @override
  _i3.RealtimeChannel onPresenceLeave(
          void Function(_i3.RealtimePresenceLeavePayload)? callback) =>
      (super.noSuchMethod(
        Invocation.method(
          #onPresenceLeave,
          [callback],
        ),
        returnValue: _FakeRealtimeChannel_1(
          this,
          Invocation.method(
            #onPresenceLeave,
            [callback],
          ),
        ),
      ) as _i3.RealtimeChannel);

  @override
  _i3.RealtimeChannel onSystemEvents(void Function(dynamic)? callback) =>
      (super.noSuchMethod(
        Invocation.method(
          #onSystemEvents,
          [callback],
        ),
        returnValue: _FakeRealtimeChannel_1(
          this,
          Invocation.method(
            #onSystemEvents,
            [callback],
          ),
        ),
      ) as _i3.RealtimeChannel);

  @override
  _i3.RealtimeChannel onEvents(
    String? type,
    _i9.ChannelFilter? filter,
    _i3.BindingCallback? callback,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #onEvents,
          [
            type,
            filter,
            callback,
          ],
        ),
        returnValue: _FakeRealtimeChannel_1(
          this,
          Invocation.method(
            #onEvents,
            [
              type,
              filter,
              callback,
            ],
          ),
        ),
      ) as _i3.RealtimeChannel);

  @override
  _i3.RealtimeChannel off(
    String? type,
    Map<String, String>? filter,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #off,
          [
            type,
            filter,
          ],
        ),
        returnValue: _FakeRealtimeChannel_1(
          this,
          Invocation.method(
            #off,
            [
              type,
              filter,
            ],
          ),
        ),
      ) as _i3.RealtimeChannel);

  @override
  _i4.Push push(
    _i10.ChannelEvents? event,
    Map<String, dynamic>? payload, [
    Duration? timeout,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #push,
          [
            event,
            payload,
            timeout,
          ],
        ),
        returnValue: _FakePush_2(
          this,
          Invocation.method(
            #push,
            [
              event,
              payload,
              timeout,
            ],
          ),
        ),
      ) as _i4.Push);

  @override
  _i6.Future<void> httpSend({
    required String? event,
    required Object? payload,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #httpSend,
          [],
          {
            #event: event,
            #payload: payload,
            #timeout: timeout,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.ChannelResponse> sendBroadcastMessage({
    required String? event,
    required Map<String, dynamic>? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendBroadcastMessage,
          [],
          {
            #event: event,
            #payload: payload,
          },
        ),
        returnValue:
            _i6.Future<_i3.ChannelResponse>.value(_i3.ChannelResponse.ok),
      ) as _i6.Future<_i3.ChannelResponse>);

  @override
  _i6.Future<_i3.ChannelResponse> send({
    required _i9.RealtimeListenTypes? type,
    String? event,
    required Map<String, dynamic>? payload,
    Map<String, dynamic>? opts = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [],
          {
            #type: type,
            #event: event,
            #payload: payload,
            #opts: opts,
          },
        ),
        returnValue:
            _i6.Future<_i3.ChannelResponse>.value(_i3.ChannelResponse.ok),
      ) as _i6.Future<_i3.ChannelResponse>);

  @override
  void updateJoinPayload(Map<String, dynamic>? payload) => super.noSuchMethod(
        Invocation.method(
          #updateJoinPayload,
          [payload],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<String> unsubscribe([Duration? timeout]) => (super.noSuchMethod(
        Invocation.method(
          #unsubscribe,
          [timeout],
        ),
        returnValue: _i6.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #unsubscribe,
            [timeout],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  dynamic onMessage(
    String? event,
    dynamic payload, [
    String? ref,
  ]) =>
      super.noSuchMethod(Invocation.method(
        #onMessage,
        [
          event,
          payload,
          ref,
        ],
      ));

  @override
  bool isMember(String? otherTopic) => (super.noSuchMethod(
        Invocation.method(
          #isMember,
          [otherTopic],
        ),
        returnValue: false,
      ) as bool);

  @override
  void rejoin([Duration? timeout]) => super.noSuchMethod(
        Invocation.method(
          #rejoin,
          [timeout],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void forceRejoin([Duration? timeout]) => super.noSuchMethod(
        Invocation.method(
          #forceRejoin,
          [timeout],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trigger(
    String? type, [
    dynamic payload,
    String? ref,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #trigger,
          [
            type,
            payload,
            ref,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String replyEventName(String? ref) => (super.noSuchMethod(
        Invocation.method(
          #replyEventName,
          [ref],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #replyEventName,
            [ref],
          ),
        ),
      ) as String);
}
