// Mocks generated by Mockito 5.4.4 from annotations
// in exhibition_buyer_app/test/providers/formula_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:exhibition_buyer_app/core/services/realtime_service.dart'
    as _i6;
import 'package:exhibition_buyer_app/features/formula/services/exchange_settings_service.dart'
    as _i5;
import 'package:exhibition_buyer_app/features/formula/services/formula_history_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRealtimeChannel_0 extends _i1.SmartFake
    implements _i2.RealtimeChannel {
  _FakeRealtimeChannel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FormulaHistoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFormulaHistoryService extends _i1.Mock
    implements _i3.FormulaHistoryService {
  MockFormulaHistoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveFormula(
    String? formula,
    String? teamId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFormula,
          [
            formula,
            teamId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getRecentFormulas(String? teamId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentFormulas,
          [teamId],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getMostUsedFormulas(
    String? teamId,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMostUsedFormulas,
          [
            teamId,
            limit,
          ],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> deleteFormula(
    String? teamId,
    String? formula,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFormula,
          [
            teamId,
            formula,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getFormulaByText(
    String? teamId,
    String? formula,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFormulaByText,
          [
            teamId,
            formula,
          ],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);
}

/// A class which mocks [ExchangeSettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExchangeSettingsService extends _i1.Mock
    implements _i5.ExchangeSettingsService {
  MockExchangeSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String?> getCurrentFormula(String? teamId) => (super.noSuchMethod(
        Invocation.method(
          #getCurrentFormula,
          [teamId],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> setDailyFormula(
    String? teamId,
    String? formula,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDailyFormula,
          [
            teamId,
            formula,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<double?> calculateWithCurrentFormula(
    String? teamId,
    double? rmbPrice,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateWithCurrentFormula,
          [
            teamId,
            rmbPrice,
          ],
        ),
        returnValue: _i4.Future<double?>.value(),
      ) as _i4.Future<double?>);
}

/// A class which mocks [RealtimeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtimeService extends _i1.Mock implements _i6.RealtimeService {
  MockRealtimeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RealtimeChannel subscribeToBooths(
    String? eventId,
    dynamic Function(dynamic)? onUpdate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToBooths,
          [
            eventId,
            onUpdate,
          ],
        ),
        returnValue: _FakeRealtimeChannel_0(
          this,
          Invocation.method(
            #subscribeToBooths,
            [
              eventId,
              onUpdate,
            ],
          ),
        ),
      ) as _i2.RealtimeChannel);

  @override
  _i2.RealtimeChannel subscribeToPhotos(
    String? boothId,
    dynamic Function(dynamic)? onUpdate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToPhotos,
          [
            boothId,
            onUpdate,
          ],
        ),
        returnValue: _FakeRealtimeChannel_0(
          this,
          Invocation.method(
            #subscribeToPhotos,
            [
              boothId,
              onUpdate,
            ],
          ),
        ),
      ) as _i2.RealtimeChannel);

  @override
  _i2.RealtimeChannel subscribeToFlags(
    String? photoId,
    dynamic Function(dynamic)? onUpdate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToFlags,
          [
            photoId,
            onUpdate,
          ],
        ),
        returnValue: _FakeRealtimeChannel_0(
          this,
          Invocation.method(
            #subscribeToFlags,
            [
              photoId,
              onUpdate,
            ],
          ),
        ),
      ) as _i2.RealtimeChannel);

  @override
  _i2.RealtimeChannel subscribeToEvents(
    String? teamId,
    dynamic Function(dynamic)? onUpdate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToEvents,
          [
            teamId,
            onUpdate,
          ],
        ),
        returnValue: _FakeRealtimeChannel_0(
          this,
          Invocation.method(
            #subscribeToEvents,
            [
              teamId,
              onUpdate,
            ],
          ),
        ),
      ) as _i2.RealtimeChannel);

  @override
  _i2.RealtimeChannel subscribeToFormulaHistory(
    String? teamId,
    dynamic Function(dynamic)? onUpdate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToFormulaHistory,
          [
            teamId,
            onUpdate,
          ],
        ),
        returnValue: _FakeRealtimeChannel_0(
          this,
          Invocation.method(
            #subscribeToFormulaHistory,
            [
              teamId,
              onUpdate,
            ],
          ),
        ),
      ) as _i2.RealtimeChannel);

  @override
  _i2.RealtimeChannel subscribeToExchangeSettings(
    String? teamId,
    dynamic Function(dynamic)? onUpdate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToExchangeSettings,
          [
            teamId,
            onUpdate,
          ],
        ),
        returnValue: _FakeRealtimeChannel_0(
          this,
          Invocation.method(
            #subscribeToExchangeSettings,
            [
              teamId,
              onUpdate,
            ],
          ),
        ),
      ) as _i2.RealtimeChannel);

  @override
  _i4.Future<void> unsubscribe(_i2.RealtimeChannel? channel) =>
      (super.noSuchMethod(
        Invocation.method(
          #unsubscribe,
          [channel],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unsubscribeAll() => (super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
