#!/bin/bash

# Manual Web App Testing Checklist
# Run this after starting the local server: python -m http.server 8000 -d build/web

echo "========================================"
echo "Manual Web App Testing Checklist"
echo "========================================"
echo ""

# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}Prerequisites:${NC}"
echo "  [1] Local server running at http://localhost:8000/"
echo "  [2] Browser open to http://localhost:8000/"
echo "  [3] Browser DevTools open (F12)"
echo ""

echo -e "${GREEN}Test 1: Initial Load${NC}"
echo "  [ ] Page loads without errors"
echo "  [ ] Console shows no red errors (warnings OK)"
echo "  [ ] Login form visible in English"
echo "  [ ] Email and Password fields visible"
echo "  [ ] 'Register' link visible"
echo ""

echo -e "${GREEN}Test 2: Registration Flow${NC}"
echo "  [ ] Click 'Register' link"
echo "  [ ] Registration form appears"
echo "  [ ] Form shows: Email, Password, Confirm Password, Team Name, Role selector"
echo "  [ ] Role options: Buyer (default) and Remote Team"
echo "  [ ] Fill form with test data:"
echo "      Email: manual_test_$(date +%s)@example.com"
echo "      Password: Test123456"
echo "      Confirm: Test123456"
echo "      Team: Manual Test Team"
echo "      Role: Buyer"
echo "  [ ] Click 'Register' button"
echo "  [ ] Wait 2-3 seconds"
echo "  [ ] Check console for errors"
echo "  [ ] Should redirect to 'Select Event' page"
echo "  [ ] No error messages shown"
echo ""

echo -e "${GREEN}Test 3: Login Flow${NC}"
echo "  [ ] Navigate back to login (refresh or back button)"
echo "  [ ] Enter credentials from registration"
echo "  [ ] Click 'Login' button"
echo "  [ ] Should redirect to 'Select Event' page"
echo "  [ ] User session maintained (check Application > Local Storage)"
echo ""

echo -e "${GREEN}Test 4: Event Page${NC}"
echo "  [ ] 'Select Event' header visible"
echo "  [ ] Settings icon (gear) visible in top-right"
echo "  [ ] '+' button visible for creating event"
echo "  [ ] No infinite loops or loading spinners"
echo "  [ ] Console shows no recursion errors"
echo ""

echo -e "${GREEN}Test 5: Responsive Layout${NC}"
echo "  [ ] Resize browser to mobile width (375px)"
echo "      - Layout adapts correctly"
echo "      - No horizontal scrolling"
echo "      - Text remains readable"
echo "  [ ] Resize to tablet width (768px)"
echo "      - Layout adjusts appropriately"
echo "  [ ] Resize to desktop (1200px+)"
echo "      - Login form centered with max width"
echo "      - Proper use of whitespace"
echo ""

echo -e "${GREEN}Test 6: Navigation${NC}"
echo "  [ ] Browser back button works"
echo "  [ ] Can navigate between pages without errors"
echo "  [ ] URL updates correctly"
echo "  [ ] No console errors during navigation"
echo ""

echo -e "${GREEN}Test 7: Network Requests${NC}"
echo "  [ ] Open Network tab in DevTools"
echo "  [ ] Check Supabase API calls:"
echo "      - /auth/v1/signup (during registration)"
echo "      - /auth/v1/token (during login)"
echo "      - /rest/v1/teams (after login)"
echo "      - /rest/v1/users (after login)"
echo "  [ ] All return 200 or 201 status"
echo "  [ ] No 401 (unauthorized) errors"
echo "  [ ] No 500 (server) errors"
echo ""

echo -e "${GREEN}Test 8: Error Handling${NC}"
echo "  [ ] Try registering with mismatched passwords"
echo "      - Should show validation error"
echo "  [ ] Try registering with existing email"
echo "      - Should show appropriate error"
echo "  [ ] Try login with wrong password"
echo "      - Should show error message"
echo "  [ ] Try login with non-existent email"
echo "      - Should show error message"
echo ""

echo -e "${GREEN}Test 9: Performance${NC}"
echo "  [ ] Initial page load < 3 seconds"
echo "  [ ] Login/Registration response < 2 seconds"
echo "  [ ] No memory leaks (check Memory tab)"
echo "  [ ] Animations smooth (if any)"
echo ""

echo -e "${GREEN}Test 10: Browser Compatibility${NC}"
echo "  [ ] Test in Chrome/Edge"
echo "  [ ] Test in Firefox (if available)"
echo "  [ ] Test in mobile browser (if available)"
echo ""

echo "========================================"
echo -e "${YELLOW}Common Issues to Watch For:${NC}"
echo "  - RLS policy errors (403/401 from Supabase)"
echo "  - Infinite recursion errors"
echo "  - Missing environment variables"
echo "  - CORS errors"
echo "  - Base href issues (404s for assets)"
echo "  - Chinese text displaying as boxes"
echo ""

echo "========================================"
echo -e "${YELLOW}After Testing:${NC}"
echo "  1. Document any issues found"
echo "  2. Check LOCAL_E2E_STATUS.md for agent results"
echo "  3. Run: bash validate_before_push.sh"
echo "  4. If all pass → Ready to push to GitHub"
echo "========================================"
